const movies = [
  "Avatar",
  "American Psycho",
  "Apocalypse Now",
  "Back to the Future",
  "Braveheart",
  "Black Panther",
  "Casablanca",
  "Citizen Kane",
  "The Dark Knight",
  "The Departed",
  "E.T. the Extra-Terrestrial",
  "The Exorcist",
  "Forrest Gump",
  "The Godfather",
  "Gladiator",
  "Goodfellas",
  "The Green Mile",
  "The Godfather: Part II",
  "The Godfather: Part III",
  "The Great Gatsby",
  "The Godfather: Part III",
  "The Incredibles",
  "Inception",
  "The Jungle Book",
  "Jurassic Park",
  "Jaws",
  "The Lion King",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King",
  "The Matrix",
  "The Martian",
  "Mission: Impossible",
  "Mission: Impossible II",
  "Mission: Impossible III",
  "The Notebook",
  "The Prestige",
  "Pulp Fiction",
  "Psycho",
  "Raiders of the Lost Ark",
  "Rocky",
  "The Shawshank Redemption",
  "Schindler's List",
  "Se7en",
  "Spider-Man: Homecoming",
  "Star Wars: Episode IV - A New Hope",
  "Star Wars: Episode V - The Empire Strikes Back",
  "Star Wars: Episode VI - Return of the Jedi",
  "Saving Private Ryan",
  "The Silence of the Lambs",
  "Titanic",
  "The Terminator",
  "Terminator 2: Judgment Day",
  "The Shining",
  "Toy Story",
  "The Usual Suspects",
  "Up",
  "The Wizard of Oz",
  "Whiplash",
  "X-Men",
  "X-Men: Days of Future Past",
  "X-Men: Apocalypse",
  "Young Frankenstein",
  "Zootopia",
  "Zero Dark Thirty",
  "Zodiac",
  "A Clockwork Orange",
  "A Few Good Men",
  "A Streetcar Named Desire",
  "Annie Hall",
  "Apocalypto",
  "Blade Runner",
  "Bonnie and Clyde",
  "Cinderella Man",
  "Das Boot",
  "Dead Poets Society",
  "Die Hard",
  "Eternal Sunshine of the Spotless Mind",
  "Fargo",
  "Finding Nemo",
  "Gone with the Wind",
  "Heat",
  "Hotel Rwanda",
  "Into the Wild",
  "JFK",
  "Kill Bill: Vol. 1",
  "La La Land",
  "Lawrence of Arabia",
  "Mad Max: Fury Road",
  "Midnight in Paris",
  "Million Dollar Baby",
  "Monty Python and the Holy Grail",
  "No Country for Old Men",
  "Oldboy",
  "Pan's Labyrinth",
  "Platoon",
  "Raging Bull",
  "Requiem for a Dream",
  "Reservoir Dogs",
  "Scarface",
  "Shutter Island",
  "Snatch",
  "Taxi Driver",
  "The Big Lebowski",
  "The Blues Brothers",
  "The Deer Hunter",
  "The Elephant Man",
  "The Grand Budapest Hotel",
  "The Graduate",
  "The Great Escape",
  "The Green Hornet",
  "The Hurt Locker",
  "The Maltese Falcon",
  "The Prestige",
  "The Right Stuff",
  "The Sound of Music",
  "The Sting",
  "The Truman Show",
  "The Untouchables",
  "The Wolf of Wall Street",
  "There Will Be Blood",
  "To Kill a Mockingbird",
  "Trainspotting",
  "V for Vendetta",
  "Vertigo",
  "Warrior",
  "Zombieland",
  "Unforgiven",
  "Usual Suspects",
];

export default movies;
